apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  helm.sh/hook: post-install
  name: default
  labels:
    app: {{ .Release.Name }}-default-eventbus
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  nats:
    native:
      # Optional, defaults to 3. If it is < 3, set it to 3, that is the minimal requirement.
      replicas: 3
      # Optional, authen strategy, "none" or "token", defaults to "none"
      auth: token
